### ISSUE TITLE
Does flow order need changing?

### ISSUE THREAD

**Issue by timkinnane** [capistrano/npm#12]
I've found for my workflow that the default attachment of npm:install is too early.
It runs before my deploy repo has been cloned, so it doesn't have the updated package.json, thus doesn't install the correct node modules for the current version.

I've kinda hack solved it, by removing the task from 'before :updated' and reattaching after.
```
Rake::Task['deploy:updated'].prerequisites.delete('npm:install') # don't run npm before repo updated
after :updated, 'npm:install' # has to run after git clone to get updated pacjage.json
````
I'm wondering if instead it's worth doing a fork, changing the default, then pull request?

**Comment by swalkinshaw** [comment]
`before deploy:updated` is the correct hook to use. Every Capistrano extension for a package manager uses it as far as I know. Including [Bundler](https://github.com/capistrano/bundler/blob/master/lib/capistrano/tasks/bundler.cap#L53) which is the "canonical" one.

You can see the flow here: http://capistranorb.com/documentation/getting-started/flow/. `git:create_release` happens during `deploy:updating`.

So I have no idea what's happening in your case. You could an older version of Capistrano if it's new. Could be a new regression.

**Comment by timkinnane** [comment]
Yes I found it was a configuration issue with something else. Thanks for the extra info and quick support.
