### ISSUE TITLE
Doesn't work if server uses nvm to manage npm

### ISSUE THREAD

**Issue by akshah123** [capistrano/npm#13]
I get following error while running cap deploy:

```
 /usr/bin/env: npm
 : No such file or directory
```

I believe this is because I have nvm that manages npm on the server.

**Comment by swalkinshaw** [comment]
You need to modify your [command map](https://github.com/capistrano/sshkit#the-command-map) for npm.

```ruby
SSHKit.config.command_map[:npm] = '/path/to/npm'
```

**Comment by johndegey** [comment]
in 2022, works directly with package capistrano/nvm
