### ISSUE TITLE
Capistrano 3 `sudo` npm install

### ISSUE THREAD

**Issue by mtyeh411** [capistrano/npm#14]
this is more of an observation/request for clarification than an issue:

based on #1, `try_sudo` is being invoked for the `npm install` ... however, it seems that Capistrano 3 has deprecated `try_sudo` (and the `use_sudo` configuration setting).  i guess the current stance for Capistrano 3 is to configure proper user groups & privileges instead?  i assume `try_sudo` would stay in the npm cap task for Capistrano 2 compatibility?

**Comment by swalkinshaw** [comment]
#1 is pretty old, check the current codebase as it does not use `try_sudo`. This library is only Cap 3 compatible.
