### ISSUE TITLE
capistrano/npm + yarn - npm = capistrano/yarn

### ISSUE THREAD

**Issue by panozzaj** [capistrano/npm#20]
Hello, I am not sure if this is the best place, but I wanted to start a discussion about how to create a new official Capistrano package.

Recently the [Yarn JavaScript package manager](https://yarnpkg.com/) was released. It is similar to NPM, which Capistrano has support for in [capistrano/npm](https://github.com/capistrano/npm) and which we have used at my place of work. I (and others) [forked this repo](https://github.com/OurHealth/capistrano-yarn) to add Yarn support, but it might make sense to reduce effort duplication and to have a canonical gem/repo for installation.

What is the best way to create an official Capistrano gem / repo? I tried quickly looking at http://capistranorb.com/ and on the [Github organization page for capistrano](https://github.com/capistrano), but didn't see advice there (may have missed it though.)

Thanks for your help!

**Comment by robdvr** [comment]
@panozzaj I'm also looking at implementing this as well. I was able to achieve it with a custom command and hooking to before_publishing

**Comment by panozzaj** [comment]
FYI, we needed to change our capistrano-yarn configuration to not use the `--production` flag to get around bugs in Yarn when installing with that flag. See https://github.com/yarnpkg/yarn/issues/1808 for an example, although it seems like there are several issues filed that relate to this issue at https://github.com/yarnpkg/yarn/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aopen%20production. So on our fork, I set:

```
set :yarn_flags, ''
```

**Comment by antoligy** [comment]
What would be nice if it were possible to conditionally run yarn if it can be detected, that'd allow for a near seamless upgrade just on the merit of having it installed.

Other features such as utilising lockfiles without a six-year-wait would be improvements

**Comment by panozzaj** [comment]
> What would be nice if it were possible to conditionally run yarn if it can be detected, that'd allow for a near seamless upgrade just on the merit of having it installed.

That is an interesting idea that could speed up adoption. I probably would continue on trying to create an official repository for this without the yarn detection feature, but I hadn't thought of that and it would improve flexibility.

> Other features such as utilising lockfiles without a six-year-wait would be improvements

Not sure I fully understand this comment.

**Comment by panozzaj** [comment]
FWIW we ended up using https://github.com/panozzaj/capistrano-yarn in production for quite some time, I consider it a good starting point if others are looking to use Capistrano with Yarn.
