### ISSUE TITLE
Capistrano/npm is not working

### ISSUE THREAD

**Issue by Deimos620** [capistrano/npm#21]
I am trying to deploy Rails app , that has some assets which should be installed via bower.
But when I add the "capistrano/npm' and 'capistrano/bower' ,  capistrano can not find the npm binary so can not install bower totally.
Here is error message:

DEBUG [432a0042] Command: cd /home/ubuntu/apps/datraks/releases/20170630155025 && /usr/bin/env npm install --production --silent --no-progress

DEBUG [432a0042]       /usr/bin/env: npm: No such file or directory

I already have installed npm in server... Is there any solution to fix this?

**Comment by dmitry** [comment]
You have to check first if it's exists in your bash environment used by capistrano.

**Comment by sushant12** [comment]
@dmitry you are right. $PATH is missing those node path. How do I add them to it???

This is what i am doing `set :default_env, { path: "PATH=$PATH:/home/deploy/.nvm/versions/node/v10.15.1/bin" }` but it is not working.

**Comment by chongfai13** [comment]
any solution?
