### ISSUE TITLE
Empty node_modules dir

### ISSUE THREAD

**Issue by luizguilhermefr** [capistrano/npm#22]
Added the configs according to README.

Added `set :linked_dirs, %w{node_modules}` to deploy file.

Addes `set :npm_target_path, -> { release_path.join('node_modules') }` to deploy file.

The deploy applies `npm install` but the folder end up empty.

My `package.json`:

```json
{
  "private": true,
  "scripts": {},
  "devDependencies": {},
  "dependencies": {
    "express": "^4.16.2",
    "redis": "^2.8.0",
    "socket.io": "^2.0.4"
  }
}
```

**Comment by NARKOZ** [comment]
Point your `npm_target_path` to the place where `package.json` is located.
