### ISSUE TITLE
Put node_modules in linked_dirs?

### ISSUE THREAD

**Issue by vendruscolo** [capistrano/npm#7]
As the title suggests, what do you think about it?
The main advantage would be to speed up deploys, and as I see bundler plugin does a similar thing (although Bundler supports saving to a different path natively, npm will always install to `./node_modules`).

I don't know if this is possible from the npm plugin itself (I have little Ruby and capistrano internals knowledge), but we can at least give a hint to users in the read me.

At the moment I simply added

```
set :linked_dirs, %w{node_modules}
```

in `deploy.rb` and it works perfectly.

Thanks.

**Comment by c0** [comment]
@swalkinshaw npm's cache doesn't include anything compiled. For example, [`node-sass`](https://www.npmjs.com/package/node-sass) compiles libsass on each of our deploys (even though the src is cached).

**Comment by swalkinshaw** [comment]
@c0 never knew that, thanks. But even so there's an extension to manage this: https://github.com/capistrano/copy-files

**Comment by milushov** [comment]
@c0 good pint, so what you can suggest for speed up `npm install` during deployment? How can I skip compilation with `capistrano/copy-files` for `node-sass` for example?

**Comment by lichtamberg** [comment]
+1 I would also like to know..

**Comment by dmitry** [comment]
I think it's a good idea to reopen and discuss on this issue and document all this stuff in the readme.

**Comment by andyexeter** [comment]
@milushov @lichtamberg to skip compilation in node-sass you just need to use copy-files to copy the `node_modules` directory from the previous release:

```ruby
set :copy_files, ['node_modules']
```
You may also want to prune the directory before `npm install` gets called:

```ruby
before 'npm:install', 'npm:prune'
```
